# Generated by Django 6.0.6 on 2026-06-12 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_account', models.CharField(max_length=30, unique=True)),
                ('currency_code', models.SmallIntegerField(default=484)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='GmrFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('download_date', models.DateTimeField()),
                ('total_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmr_files', to='GeneralTransactions.merchant')),
            ],
            options={
                'db_table': 'gmr_files',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cod_seller', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_scheme', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='GeneralTransactions.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='GeneralTransactions.merchant')),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_terminal', models.CharField(db_index=True, max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='GeneralTransactions.seller')),
            ],
            options={
                'db_table': 'terminals',
                'unique_together': {('seller', 'id_terminal')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_transaction', models.CharField(max_length=100, unique=True)),
                ('id_settlement', models.CharField(blank=True, max_length=100, null=True)),
                ('id_external_order', models.CharField(blank=True, max_length=100, null=True)),
                ('id_external_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_authorization', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_arn', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_stan', models.BigIntegerField(blank=True, null=True)),
                ('des_mov_type', models.CharField(blank=True, max_length=50, null=True)),
                ('des_identity_origin_type', models.CharField(blank=True, max_length=100, null=True)),
                ('nam_identity_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('tx_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tx_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tx_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('op_type', models.CharField(blank=True, max_length=50, null=True)),
                ('des_authorizer_switch', models.CharField(blank=True, max_length=100, null=True)),
                ('des_settlement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('des_settlement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_transaction', models.DateField(blank=True, null=True)),
                ('tim_transaction', models.TimeField(blank=True, null=True)),
                ('num_timezone', models.SmallIntegerField(blank=True, null=True)),
                ('dat_settlement', models.DateField(blank=True, null=True)),
                ('dat_settled', models.DateField(blank=True, null=True)),
                ('dat_original_transaction', models.DateField(blank=True, null=True)),
                ('des_card_entry_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('num_card', models.CharField(blank=True, max_length=30, null=True)),
                ('card_funding', models.CharField(blank=True, max_length=30, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('card_interchange', models.CharField(blank=True, max_length=100, null=True)),
                ('card_country', models.CharField(blank=True, max_length=5, null=True)),
                ('card_product', models.CharField(blank=True, max_length=100, null=True)),
                ('des_authentication_method', models.CharField(blank=True, max_length=100, null=True)),
                ('amt_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cod_currency', models.SmallIntegerField(blank=True, null=True)),
                ('amt_net_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_total_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_original_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('id_original_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('mdr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amt_mdr', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pct_mdr', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('pct_mdr_transaction_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('amt_mdr_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pct_mdr_vat', models.CharField(blank=True, max_length=20, null=True)),
                ('amt_interchange', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pct_interchange', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('amt_scheme_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pct_scheme_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('amt_markup', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pct_markup', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('amt_fix_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('flag_installment', models.BooleanField(blank=True, null=True)),
                ('des_installment_plan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('des_installment_schema', models.CharField(blank=True, max_length=100, null=True)),
                ('num_total_installments', models.SmallIntegerField(blank=True, null=True)),
                ('num_installment', models.SmallIntegerField(blank=True, null=True)),
                ('amt_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_total_installment_tx', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_installment_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('flag_cashback', models.BooleanField(blank=True, null=True)),
                ('amt_cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amt_fee_cashback', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('flag_dcc', models.BooleanField(blank=True, null=True)),
                ('cod_currency_dcc', models.SmallIntegerField(blank=True, null=True)),
                ('amt_dcc_rebate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='GeneralTransactions.gmrfile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='GeneralTransactions.seller')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='GeneralTransactions.terminal')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['dat_transaction'], name='transaction_dat_tra_15b778_idx'), models.Index(fields=['dat_settlement'], name='transaction_dat_set_f856be_idx'), models.Index(fields=['seller'], name='transaction_seller__083d37_idx'), models.Index(fields=['card_brand'], name='transaction_card_br_d5bf31_idx'), models.Index(fields=['tx_status'], name='transaction_tx_stat_f1f194_idx')],
            },
        ),
    ]
